 public static void main(String[] args) {
      
      int numeroProduto = "ABC123";
      double precoProduto = 25;
      
      String descricaoProduto;
      
      System.out.println("Descrição do Produto: " + descricaoProduto);
      
      descricaoProduto = "Fone de ouvido Bluetooth";
      
      System.out.println("Descrição do Produto: " + descricaoProduto);
      System.out.println("Número: " + numeroProduto);
      System.out.println("Preço: $" + precoProduto);
      System.out.println("Descrição: " + descricaoProduto);
    }
}
