class ControleEstoque {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
        
        String smartphone;
        String laptop;
        String foneBluetooth;
        
        String nomeProduto;
        String marcaProduto;
        float preçoProduto;
        int estoqueProduto;
        
        System.out.println("Dados do Smartphone:");
        System.out.println("smartphone: " +nomeProduto );
        
        System.out.println("Dados do Laptop:");
        System.out.println("smartphone: " +nomeProduto );
        
        System.out.println("Dados do Fone Bluetooth:");
        System.out.println("smartphone: " +nomeProduto );
        
        
