class HelloWorld {
    

    public static void main(String[] args) {
        
        String nome = "Andrey"
        String sobrenome = "Lovis";
        float valor = 1.2f;
        int idade = 10;
        Integer ano = 50;
        double peso = 80.5;
        boolean confirma = true;
        char sexo = 'M';
        
        Integer soma;
        
        nome = "Andrey";
        
        System.out.println("Andrey");
        System.out.println(nome + sobrenome);
        System.out.println(idade);
        System.out.println("Sua idade eh : " + idade);
      
        soma = 10 + 10;
        System.out.println("Soma e " + soma);
      
    }
    
   
}
